---
- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- include_tasks: redhat.yml
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat') and ansible_distribution_major_version == '7'

