---
- name: create docker group
  group:
    name: "docker"
    gid: "{{ DOCKER_GROUP_ID }}"
    state: present
  when: DOCKER_GROUP_ID is defined

- name: add docker official repository gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker official repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    mode: 0644
    update_cache: yes
  register: docker_repository_added

- name: update
  apt: 
    update_cache: yes

- name: install docker-ce
  package: name={{ item }} state=present
  with_items:
    - docker-ce={{ DOCKER_VERSION }}.0~ce-0~ubuntu
    - python-setuptools
    - python-pip

- name: install docker & docker-compose
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - { name: docker, version: 2.5.0 }
    - { name: docker-compose, version: 1.15.0 }
  register: result
  until: result|succeeded
  retries: 40
  delay: 3

- name: update docker configuration with the data directory
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: '^ExecStart='
    line: 'ExecStart=/usr/bin/dockerd -g {{ DOCKER_DATA }} -H fd://'
  notify: restart docker
  when: DOCKER_DATA is defined

- name: start and enable at boot docker
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started

- name: add telegraf user to docker group
  user:
    name: telegraf
    groups: docker
    append: yes

- name: configure logrotate
  blockinfile:
    path: /etc/logrotate.d/docker
    create: yes
    block: |
      /var/lib/docker/containers/*/*.log {
        rotate 7
        daily
        compress
        missingok
        delaycompress
        copytruncate
      }
    owner: root
    mode: 0644

- name: check if filebeat is installed
  stat:
    path: /etc/filebeat/conf.d
  register: filebeatconf

- name: configure filebeat
  blockinfile:
    path: /etc/filebeat/conf.d/docker.yml
    create: yes
    block: |
      filebeat.prospectors:
      - input_type: log
        paths:
          - /var/lib/docker/containers/*/*.log
  when: filebeatconf.stat.exists and filebeatconf.stat.isdir == true
  notify:
    - restart filebeat

- name: check if telegraf is installed
  stat:
    path: /etc/telegraf/telegraf.d/
  register: telegrafconf

- name: configure telegraf
  blockinfile:
    path: /etc/telegraf/telegraf.d/docker.conf
    create: yes
    block: |
      [[inputs.docker]]
        container_name_include = []
        container_name_exclude = []
        timeout = "10s"
    owner: root
    mode: 0644
  when: telegrafconf.stat.exists and telegrafconf.stat.isdir == true
  notify:
    - restart telegraf

- name: register docker in consul
  consul:
    service_name: docker
    script: service docker status
    interval: 1m
  ignore_errors: True
